version: '3.8'

services:
  tello-backend:
    image: tello-monitor/backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - tello-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  tello-frontend:
    image: tello-monitor/frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - tello-backend
    networks:
      - tello-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  webrtc-server:
    image: tello-monitor/webrtc:latest
    ports:
      - "8000:8000"
    networks:
      - tello-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tello-frontend
      - tello-backend
    networks:
      - tello-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  tello-network:
    driver: overlay
    attachable: true

volumes:
  drone_data:
    driver: local